#!/usr/bin/env bash
#
# L1 half of the devnet deployment: the two traded tokens, a real Uniswap V2
# venue for a solver to route through, and `Executor` (which constructs
# `Relayer` in its own constructor).
#
# Idempotent only in the sense that re-running it deploys a fresh set. Addresses
# land in script/deployments.env, which script/install-l2.sh and script/e2e.sh
# both read.
#
#     bash script/install-l1.sh
set -euo pipefail
cd "$(dirname "$0")/.."

set -a; source script/dev.env; set +a
source script/lib.sh

: > "$DEPLOYMENTS"
printf '# Generated by script/install-l1.sh at %s\n' "$(date -u +%FT%TZ)" >> "$DEPLOYMENTS"

L1="--rpc-url $L1_RPC --private-key $DEPLOYER_KEY"

step "Preflight"
info "L1 $L1_RPC  chain $L1_CHAIN_ID  block $(cast block-number --rpc-url "$L1_RPC")"
info "L2 $L2_RPC  chain $L2_CHAIN_ID  block $(cast block-number --rpc-url "$L2_RPC")"
[ "$(cast code "$EEZ_REGISTRY_ADDRESS" --rpc-url "$L1_RPC")" != "0x" ] \
    || die "no EEZ registry at $EEZ_REGISTRY_ADDRESS on L1 -- is this the right enclave?"

step "Tokens"
# `Tok` is the fixture's minimal ERC-20: the whole supply is minted to the
# deployer, which then distributes. Reused rather than duplicated so the devnet
# trades the same token the suite does.
#
# Both are 18 decimals, including the one called USDC. Real USDC is 6, and the
# difference is invisible to every invariant here -- prices are ratios and
# `PRICE_SCALE` pins only index 0 -- but it is why the numbers below read as
# `2000 ether` rather than `2000e6`.
USDC=$(forge create test/helpers/SettlementFixture.sol:Tok $L1 --broadcast --json \
    --constructor-args "USDC" 1000000000000000000000000000000 | jq -r .deployedTo)
record USDC "$USDC"
WETH=$(forge create test/helpers/SettlementFixture.sol:Tok $L1 --broadcast --json \
    --constructor-args "WETH" 1000000000000000000000000000000 | jq -r .deployedTo)
record WETH "$WETH"

step "Uniswap V2"
bc() { jq -r .bytecode "$1" | sed 's/^\(0x\)\?/0x/'; }

FACTORY=$(cast send $L1 --json --create \
    "$(bc node_modules/@uniswap/v2-core/build/UniswapV2Factory.json)" \
    "constructor(address)" "$DEPLOYER" | jq -r .contractAddress)
record FACTORY "$FACTORY"

# UniswapV2Router02's constructor demands a WETH address and stores it immutably.
# Nothing in this harness takes an ETH path -- the settlement pair is two plain
# ERC-20s -- so this exists only to satisfy the constructor.
ROUTER_WETH=$(cast send $L1 --json --create \
    "$(bc node_modules/canonical-weth/build/contracts/WETH9.json)" | jq -r .contractAddress)
record ROUTER_WETH "$ROUTER_WETH"

ROUTER=$(cast send $L1 --json --create \
    "$(bc node_modules/@uniswap/v2-periphery/build/UniswapV2Router02.json)" \
    "constructor(address,address)" "$FACTORY" "$ROUTER_WETH" | jq -r .contractAddress)
record ROUTER "$ROUTER"

step "Liquidity: 20,000,000 USDC / 10,000 WETH"
# Deep enough that the 2,000 USDC leg in phase 2 of the e2e moves the price by
# about 1bp, so the settlement's residue is essentially the 0.3% Uniswap fee and
# nothing else. A thin pool would make the residue assertion a slippage
# measurement rather than an I17 check.
cast send $L1 "$USDC" 'approve(address,uint256)' "$ROUTER" "$(cast max-uint)" >/dev/null
cast send $L1 "$WETH" 'approve(address,uint256)' "$ROUTER" "$(cast max-uint)" >/dev/null
cast send $L1 "$ROUTER" \
    'addLiquidity(address,address,uint256,uint256,uint256,uint256,address,uint256)' \
    "$USDC" "$WETH" \
    20000000000000000000000000 10000000000000000000000 0 0 \
    "$DEPLOYER" "$(( $(l1_now) + 3600 ))" >/dev/null

PAIR=$(cast call "$FACTORY" 'getPair(address,address)(address)' "$USDC" "$WETH" --rpc-url "$L1_RPC")
record PAIR "$PAIR"
info "reserves: $(cast call "$PAIR" 'getReserves()(uint112,uint112,uint32)' --rpc-url "$L1_RPC" | tr '\n' ' ')"

step "Executor (constructs Relayer)"
# §13.2 is open and this address is not an answer to it -- see script/dev.env.
info "windfallRecipient = $WINDFALL_RECIPIENT_DEVNET_PLACEHOLDER  (devnet placeholder, §13.2 unresolved)"
EXECUTOR=$(forge create src/Executor.sol:Executor $L1 --broadcast --json --constructor-args \
    "$EEZ_REGISTRY_ADDRESS" "$EEZ_ROLLUP_ID" "$WINDFALL_RECIPIENT_DEVNET_PLACEHOLDER" | jq -r .deployedTo)
record EXECUTOR "$EXECUTOR"
RELAYER=$(cast call "$EXECUTOR" 'relayer()(address)' --rpc-url "$L1_RPC")
record RELAYER "$RELAYER"
record WINDFALL "$WINDFALL_RECIPIENT_DEVNET_PLACEHOLDER"

step "Funding the traders"
# Alice and Bob are prefunded in L2 genesis but hold no L1 ETH, and each needs
# exactly one L1 transaction: the Relayer approval.
for who in "$ALICE" "$BOB"; do
    cast send $L1 "$who" --value 1ether >/dev/null
done
# Alice sells 2,000 USDC in each of the two settlements; Bob sells 1 WETH in the
# first and nothing in the second.
cast send $L1 "$USDC" 'transfer(address,uint256)' "$ALICE" 4000000000000000000000 >/dev/null
cast send $L1 "$WETH" 'transfer(address,uint256)' "$BOB"   1000000000000000000    >/dev/null
info "alice USDC $(cast from-wei "$(balance_of "$USDC" "$ALICE" "$L1_RPC")")"
info "bob   WETH $(cast from-wei "$(balance_of "$WETH" "$BOB" "$L1_RPC")")"

step "Approvals -> Relayer, never Executor"
# §3.1 / I13: `Relayer` holds every approval and answers only to `Executor`. An
# account that approved `Executor` instead fails at pull time in a way that reads
# as a signature problem, which is the single most expensive way to get this
# wrong.
cast send --rpc-url "$L1_RPC" --private-key "$ALICE_KEY" "$USDC" \
    'approve(address,uint256)' "$RELAYER" "$(cast max-uint)" >/dev/null
cast send --rpc-url "$L1_RPC" --private-key "$BOB_KEY" "$WETH" \
    'approve(address,uint256)' "$RELAYER" "$(cast max-uint)" >/dev/null
expect_eq "alice USDC allowance -> Relayer" \
    "$(cast call "$USDC" 'allowance(address,address)(uint256)' "$ALICE" "$RELAYER" --rpc-url "$L1_RPC" | awk '{print $1}')" \
    "$(cast max-uint)"
expect_eq "bob WETH allowance -> Relayer" \
    "$(cast call "$WETH" 'allowance(address,address)(uint256)' "$BOB" "$RELAYER" --rpc-url "$L1_RPC" | awk '{print $1}')" \
    "$(cast max-uint)"
expect_eq "alice USDC allowance -> Executor stays zero (I13)" \
    "$(cast call "$USDC" 'allowance(address,address)(uint256)' "$ALICE" "$EXECUTOR" --rpc-url "$L1_RPC" | awk '{print $1}')" \
    "0"

step "L1 done"
info "wrote $DEPLOYMENTS"
[ "$FAILURES" -eq 0 ] || die "$FAILURES check(s) failed"
